# Add this section to your template.yaml after the existing Lambda functions

# ==========================================
# AI Service Lambda Functions
# ==========================================

# Content Generation Lambda
AiContentGenerationFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-ai-content-generation-${Environment}
    CodeUri: infrastructure/lambda-functions/ai-service/content-generation/
    Handler: handler.handler
    Runtime: nodejs22.x
    Timeout: 300 # 5 minutes for AI processing
    MemorySize: 2048 # Higher memory for AI workloads
    Role: !GetAtt AiProcessingLambdaRole.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        S3_BUCKET_NAME: !Ref StorageBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
        BEDROCK_REGION: !Ref AWS::Region
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: AIService
      Function: ContentGeneration

# Research Lambda
AiResearchFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-ai-research-${Environment}
    CodeUri: infrastructure/lambda-functions/ai-service/research/
    Handler: handler.handler
    Runtime: nodejs22.x
    Timeout: 300
    MemorySize: 2048
    Role: !GetAtt AiProcessingLambdaRole.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        S3_BUCKET_NAME: !Ref StorageBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
        BEDROCK_REGION: !Ref AWS::Region
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
        TAVILY_API_KEY: !Ref TavilyAPISecret
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: AIService
      Function: Research

# Brand Analysis Lambda
AiBrandAnalysisFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-ai-brand-analysis-${Environment}
    CodeUri: infrastructure/lambda-functions/ai-service/brand-analysis/
    Handler: handler.handler
    Runtime: nodejs22.x
    Timeout: 300
    MemorySize: 2048
    Role: !GetAtt AiProcessingLambdaRole.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        S3_BUCKET_NAME: !Ref StorageBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
        BEDROCK_REGION: !Ref AWS::Region
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: AIService
      Function: BrandAnalysis

# ==========================================
# Integration Service Lambda Functions
# ==========================================

# OAuth Integration Lambda
IntegrationOAuthFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-integration-oauth-${Environment}
    CodeUri: infrastructure/lambda-functions/integration-service/oauth/
    Handler: handler.handler
    Runtime: nodejs22.x
    Timeout: 30
    MemorySize: 512
    Role: !GetAtt IntegrationServiceLambdaRole.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
        GOOGLE_CLIENT_ID: !Ref GoogleOAuthSecret
        GOOGLE_CLIENT_SECRET: !Ref GoogleOAuthSecret
        GOOGLE_REDIRECT_URI: !If
          - IsProduction
          - https://bayoncoagent.app/oauth/callback
          - http://localhost:3000/oauth/callback
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: IntegrationService
      Function: OAuth

# File Storage Lambda
IntegrationFileStorageFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-integration-file-storage-${Environment}
    CodeUri: infrastructure/lambda-functions/integration-service/file-storage/
    Handler: handler.handler
    Runtime: nodejs22.x
    Timeout: 30
    MemorySize: 512
    Role: !GetAtt IntegrationServiceLambdaRole.Arn
    Environment:
      Variables:
        S3_BUCKET_NAME: !Ref StorageBucket
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: IntegrationService
      Function: FileStorage

# ==========================================
# Lambda Roles
# ==========================================

# AI Processing Lambda Role
AiProcessingLambdaRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub bayon-coagent-ai-processing-lambda-${Environment}
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
    Policies:
      - PolicyName: DynamoDBAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
                - dynamodb:BatchWriteItem
              Resource:
                - !GetAtt DynamoDBTable.Arn
                - !Sub ${DynamoDBTable.Arn}/index/*
      - PolicyName: S3Access
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: !Sub ${StorageBucket.Arn}/*
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt StorageBucket.Arn
      - PolicyName: BedrockAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-*
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-*
      - PolicyName: SecretsManagerAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref TavilyAPISecret

# Integration Service Lambda Role
IntegrationServiceLambdaRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub bayon-coagent-integration-service-lambda-${Environment}
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
    Policies:
      - PolicyName: DynamoDBAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
              Resource:
                - !GetAtt DynamoDBTable.Arn
                - !Sub ${DynamoDBTable.Arn}/index/*
      - PolicyName: S3Access
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !GetAtt StorageBucket.Arn
                - !Sub ${StorageBucket.Arn}/*
      - PolicyName: SecretsManagerAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GoogleOAuthSecret
                - !Ref FacebookOAuthSecret
                - !Ref InstagramOAuthSecret
                - !Ref LinkedInOAuthSecret
                - !Ref TwitterOAuthSecret

# ==========================================
# API Gateway Resources and Methods
# ==========================================

# AI Service API Resources
AiContentResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    RestApiId: !Ref AiServiceApi
    ParentId: !GetAtt AiServiceApi.RootResourceId
    PathPart: content

AiContentGenerationMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    RestApiId: !Ref AiServiceApi
    ResourceId: !Ref AiContentResource
    HttpMethod: POST
    AuthorizationType: CUSTOM
    AuthorizerId: !Ref AiServiceCognitoAuthorizer
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AiContentGenerationFunction.Arn}/invocations
    MethodResponses:
      - StatusCode: 200
      - StatusCode: 400
      - StatusCode: 401
      - StatusCode: 500

AiResearchResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    RestApiId: !Ref AiServiceApi
    ParentId: !GetAtt AiServiceApi.RootResourceId
    PathPart: research

AiResearchMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    RestApiId: !Ref AiServiceApi
    ResourceId: !Ref AiResearchResource
    HttpMethod: POST
    AuthorizationType: CUSTOM
    AuthorizerId: !Ref AiServiceCognitoAuthorizer
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AiResearchFunction.Arn}/invocations
    MethodResponses:
      - StatusCode: 200
      - StatusCode: 400
      - StatusCode: 401
      - StatusCode: 500

AiBrandResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    RestApiId: !Ref AiServiceApi
    ParentId: !GetAtt AiServiceApi.RootResourceId
    PathPart: brand

AiBrandAnalysisMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    RestApiId: !Ref AiServiceApi
    ResourceId: !Ref AiBrandResource
    HttpMethod: POST
    AuthorizationType: CUSTOM
    AuthorizerId: !Ref AiServiceCognitoAuthorizer
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AiBrandAnalysisFunction.Arn}/invocations
    MethodResponses:
      - StatusCode: 200
      - StatusCode: 400
      - StatusCode: 401
      - StatusCode: 500

# Integration Service API Resources
IntegrationOAuthResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    RestApiId: !Ref IntegrationServiceApi
    ParentId: !GetAtt IntegrationServiceApi.RootResourceId
    PathPart: oauth

IntegrationOAuthMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    RestApiId: !Ref IntegrationServiceApi
    ResourceId: !Ref IntegrationOAuthResource
    HttpMethod: ANY
    AuthorizationType: CUSTOM
    AuthorizerId: !Ref IntegrationServiceCognitoAuthorizer
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IntegrationOAuthFunction.Arn}/invocations
    MethodResponses:
      - StatusCode: 200
      - StatusCode: 400
      - StatusCode: 401
      - StatusCode: 500

IntegrationFilesResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    RestApiId: !Ref IntegrationServiceApi
    ParentId: !GetAtt IntegrationServiceApi.RootResourceId
    PathPart: files

IntegrationFilesMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    RestApiId: !Ref IntegrationServiceApi
    ResourceId: !Ref IntegrationFilesResource
    HttpMethod: ANY
    AuthorizationType: CUSTOM
    AuthorizerId: !Ref IntegrationServiceCognitoAuthorizer
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IntegrationFileStorageFunction.Arn}/invocations
    MethodResponses:
      - StatusCode: 200
      - StatusCode: 400
      - StatusCode: 401
      - StatusCode: 500

# ==========================================
# Lambda Permissions
# ==========================================

AiContentGenerationLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref AiContentGenerationFunction
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AiServiceApi}/*

AiResearchLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref AiResearchFunction
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AiServiceApi}/*

AiBrandAnalysisLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref AiBrandAnalysisFunction
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AiServiceApi}/*

IntegrationOAuthLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref IntegrationOAuthFunction
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${IntegrationServiceApi}/*

IntegrationFileStorageLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref IntegrationFileStorageFunction
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${IntegrationServiceApi}/*

# Add these secrets if they don't exist
TavilyAPISecret:
  Type: AWS::SecretsManager::Secret
  Properties:
    Name: !Sub bayon-coagent-tavily-api-${Environment}
    Description: Tavily API key for research functionality
    SecretString: !Sub |
      {
        "apiKey": "your-tavily-api-key-here"
      }
    Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Application
        Value: BayonCoAgent
