# Minimal Lambda Addition - Add this to your existing template.yaml

# ==========================================
# API Gateway + Lambda Migration - Phase 1
# ==========================================

# AI Content Generation Lambda
AiContentGenerationFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-ai-content-generation-${Environment}
    CodeUri: infrastructure/lambda-functions/ai-content-generation/
    Handler: index.handler
    Runtime: nodejs22.x
    Timeout: 300
    MemorySize: 2048
    Role: !GetAtt ApplicationRole.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        S3_BUCKET_NAME: !Ref StorageBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
        BEDROCK_REGION: !Ref AWS::Region
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: AIService
      Function: ContentGeneration

# AI Research Lambda
AiResearchFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-ai-research-${Environment}
    CodeUri: infrastructure/lambda-functions/ai-research/
    Handler: index.handler
    Runtime: nodejs22.x
    Timeout: 300
    MemorySize: 2048
    Role: !GetAtt ApplicationRole.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        S3_BUCKET_NAME: !Ref StorageBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
        BEDROCK_REGION: !Ref AWS::Region
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Service: AIService
      Function: Research

# Add these outputs too:
AiContentGenerationFunctionArn:
  Description: AI Content Generation Lambda Function ARN
  Value: !GetAtt AiContentGenerationFunction.Arn
  Export:
    Name: !Sub ${Environment}-AiContentGenerationFunctionArn

AiResearchFunctionArn:
  Description: AI Research Lambda Function ARN
  Value: !GetAtt AiResearchFunction.Arn
  Export:
    Name: !Sub ${Environment}-AiResearchFunctionArn
