# Add this to template.yaml after the SyncSocialAnalyticsFunction (around line 3030)

# ==========================================
# Stripe Subscription Handler Lambda
# ==========================================
StripeSubscriptionHandlerFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: !Sub bayon-coagent-stripe-subscription-handler-${Environment}
    CodeUri: src/lambda/
    Handler: stripe-subscription-handler.handler
    Runtime: nodejs22.x
    Timeout: 30
    MemorySize: 512
    Role: !GetAtt ApplicationRole.Arn
    Events:
      StripeSubscriptionCreated:
        Type: EventBridgeRule
        Properties:
          EventBusName: aws.partner/stripe.com/ed_test_61ThQU3sr9KLkWPGq16ThPlt3iSQLw25fKzPmC3uK2lk
          Pattern:
            source:
              - aws.partner/stripe.com
            detail-type:
              - Stripe Event
            detail:
              type:
                - customer.subscription.created
                - customer.subscription.updated
                - customer.subscription.deleted
                - invoice.payment_succeeded
                - invoice.payment_failed
          RetryPolicy:
            MaximumRetryAttempts: 3
            MaximumEventAge: 7200 # 2 hours
          DeadLetterConfig:
            Arn: !GetAtt StripeEventDLQ.Arn
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        STRIPE_SECRET_KEY: "{{resolve:secretsmanager:bayon-stripe-secret:SecretString:secret_key}}"
        NODE_ENV: !Ref Environment
    Tags:
      Environment: !Ref Environment
      Application: BayonCoAgent
      Function: StripeSubscriptionHandler

# Dead Letter Queue for failed Stripe events
StripeEventDLQ:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: !Sub bayon-stripe-events-dlq-${Environment}
    MessageRetentionPeriod: 1209600 # 14 days
    Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Application
        Value: BayonCoAgent

# CloudWatch Alarm for Stripe DLQ
StripeEventDLQAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmName: !Sub bayon-stripe-events-dlq-alarm-${Environment}
    AlarmDescription: Alert when Stripe events fail and land in DLQ
    MetricName: ApproximateNumberOfMessagesVisible
    Namespace: AWS/SQS
    Statistic: Sum
    Period: 300
    EvaluationPeriods: 1
    Threshold: 1
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: QueueName
        Value: !GetAtt StripeEventDLQ.QueueName
    TreatMissingData: notBreaching
    AlarmActions: !If
      - HasAlarmEmail
      - - !Ref AlarmTopic
      - !Ref AWS::NoValue

# Stripe Secret in Secrets Manager
StripeSecret:
  Type: AWS::SecretsManager::Secret
  Properties:
    Name: !Sub bayon-stripe-secret-${Environment}
    Description: Stripe API secret key
    SecretString: !Sub |
      {
        "secret_key": "sk_test_placeholder"
      }
    Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Application
        Value: BayonCoAgent

# Add to Outputs section:
StripeSubscriptionHandlerFunctionArn:
  Description: Stripe Subscription Handler Lambda Function ARN
  Value: !GetAtt StripeSubscriptionHandlerFunction.Arn
  Export:
    Name: !Sub ${AWS::StackName}-StripeSubscriptionHandlerFunctionArn

StripeEventDLQUrl:
  Description: Stripe Event Dead Letter Queue URL
  Value: !Ref StripeEventDLQ
  Export:
    Name: !Sub ${AWS::StackName}-StripeEventDLQUrl

StripeSecretArn:
  Description: Stripe Secret ARN in Secrets Manager
  Value: !Ref StripeSecret
  Export:
    Name: !Sub ${AWS::StackName}-StripeSecretArn
