AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Bayon CoAgent - Serverless Infrastructure

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
    Description: Environment name

  AlarmEmail:
    Type: String
    Default: ""
    Description: Email address for CloudWatch alarms (optional)

Conditions:
  IsProduction: !Equals [!Ref Environment, production]
  HasAlarmEmail: !Not [!Equals [!Ref AlarmEmail, ""]]

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs18.x
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_REGION: !Ref AWS::Region
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
        S3_BUCKET_NAME: !Ref StorageBucket
        BEDROCK_MODEL_ID: anthropic.claude-3-5-sonnet-20241022-v2:0
        BEDROCK_REGION: !Ref AWS::Region

Resources:
  # ==========================================
  # Cognito User Pool
  # ==========================================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub bayon-coagent-${Environment}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: given_name
          Required: false
          Mutable: true
        - Name: family_name
          Required: false
          Mutable: true
        - Name: agentId
          AttributeDataType: String
          Mutable: true
        - Name: businessName
          AttributeDataType: String
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
        - SMS_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UserPoolTags:
        Environment: !Ref Environment
        Application: BayonCoAgent

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub bayon-coagent-web-${Environment}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_CUSTOM_AUTH
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes
      EnableTokenRevocation: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !If
          - IsProduction
          - https://yourdomain.com/oauth/callback
          - http://localhost:3000/oauth/callback
      LogoutURLs:
        - !If
          - IsProduction
          - https://yourdomain.com
          - http://localhost:3000

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub bayon_coagent_${Environment}
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: UserScopedAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                Resource: !GetAtt DynamoDBTable.Arn
                Condition:
                  ForAllValues:StringLike:
                    dynamodb:LeadingKeys:
                      - USER#${cognito-identity.amazonaws.com:sub}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub ${StorageBucket.Arn}/users/$${cognito-identity.amazonaws.com:sub}/*
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !GetAtt StorageBucket.Arn
                Condition:
                  StringLike:
                    s3:prefix:
                      - users/${cognito-identity.amazonaws.com:sub}/*

  # ==========================================
  # DynamoDB Table
  # ==========================================
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub BayonCoAgent-${Environment}
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: EntityType
          AttributeType: S
        - AttributeName: CreatedAt
          AttributeType: N
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: UpdatedAt
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EntityTypeIndex
          KeySchema:
            - AttributeName: EntityType
              KeyType: HASH
            - AttributeName: CreatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
            - AttributeName: UpdatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BayonCoAgent

  # ==========================================
  # S3 Storage Bucket
  # ==========================================
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bayon-coagent-storage-${Environment}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: !If [IsProduction, Enabled, Suspended]
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
          - Id: TransitionToIA
            Status: !If [IsProduction, Enabled, Disabled]
            Transitions:
              - TransitionInDays: 90
                StorageClass: STANDARD_IA
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - !If
                - IsProduction
                - https://yourdomain.com
                - http://localhost:3000
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
            MaxAge: 3000
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BayonCoAgent

  StorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageBucket
      PolicyDocument:
        Statement:
          - Sid: AllowApplicationAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt ApplicationRole.Arn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt StorageBucket.Arn
              - !Sub ${StorageBucket.Arn}/*

  # ==========================================
  # IAM Roles
  # ==========================================
  ApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub bayon-coagent-app-${Environment}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ecs-tasks.amazonaws.com
                - amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CognitoAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminUpdateUserAttributes
                  - cognito-idp:AdminDeleteUser
                  - cognito-idp:ListUsers
                Resource: !GetAtt UserPool.Arn
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource:
                  - !GetAtt DynamoDBTable.Arn
                  - !Sub ${DynamoDBTable.Arn}/index/*
                  - !Sub ${DynamoDBTable.Arn}/stream/*
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt StorageBucket.Arn
                  - !Sub ${StorageBucket.Arn}/*
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/bayon-coagent/*
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:ListFoundationModels
                  - bedrock:GetFoundationModel
                Resource:
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-*
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-*

  # ==========================================
  # CloudWatch Monitoring
  # ==========================================
  AlarmTopic:
    Type: AWS::SNS::Topic
    Condition: HasAlarmEmail
    Properties:
      TopicName: !Sub bayon-coagent-alarms-${Environment}
      DisplayName: !Sub Bayon CoAgent Alarms (${Environment})
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: email

  AuthFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${Environment}-high-auth-failures
      AlarmDescription: Alert when authentication failures exceed threshold
      MetricName: SignInThrottles
      Namespace: AWS/Cognito
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: UserPool
          Value: !Ref UserPool
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: notBreaching

  DynamoDBThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${Environment}-dynamodb-throttling
      AlarmDescription: Alert when DynamoDB requests are being throttled
      MetricName: UserErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: notBreaching

  S3ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      AlarmName: !Sub ${Environment}-s3-errors
      AlarmDescription: Alert when S3 5xx errors exceed threshold
      MetricName: 5xxErrors
      Namespace: AWS/S3
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: BucketName
          Value: !Ref StorageBucket
      AlarmActions:
        - !Ref AlarmTopic
      TreatMissingData: notBreaching

  # ==========================================
  # CloudWatch Dashboard
  # ==========================================
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub BayonCoAgent-${Environment}
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Cognito", "SignInSuccesses", {"stat": "Sum"}],
                  [".", "SignInThrottles", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Authentication Activity",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", {"stat": "Sum"}],
                  [".", "ConsumedWriteCapacityUnits", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "DynamoDB Activity",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/S3", "AllRequests", {"stat": "Sum"}],
                  [".", "4xxErrors", {"stat": "Sum"}],
                  [".", "5xxErrors", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "S3 Activity",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Bedrock", "Invocations", {"stat": "Sum"}],
                  [".", "ModelInvocationThrottles", {"stat": "Sum"}],
                  [".", "InvocationLatency", {"stat": "Average"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Bedrock Activity",
                "yAxis": {"left": {"min": 0}}
              }
            }
          ]
        }

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${Environment}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${Environment}-UserPoolClientId

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool
    Export:
      Name: !Sub ${Environment}-IdentityPoolId

  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub ${Environment}-DynamoDBTableName

  DynamoDBTableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: !Sub ${Environment}-DynamoDBTableArn

  StorageBucketName:
    Description: S3 Storage Bucket Name
    Value: !Ref StorageBucket
    Export:
      Name: !Sub ${Environment}-StorageBucketName

  StorageBucketArn:
    Description: S3 Storage Bucket ARN
    Value: !GetAtt StorageBucket.Arn
    Export:
      Name: !Sub ${Environment}-StorageBucketArn

  ApplicationRoleArn:
    Description: Application Role ARN
    Value: !GetAtt ApplicationRole.Arn
    Export:
      Name: !Sub ${Environment}-ApplicationRoleArn

  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MonitoringDashboard}

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub ${Environment}-Region
