AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Bayon CoAgent - Performance Improvements (Minimal)

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - production
    Description: Environment name

Conditions:
  IsProduction: !Equals [!Ref Environment, production]

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs22.x
    Architectures: [arm64] # 20% cost savings across all functions
    Tracing: Active
    Environment:
      Variables:
        NODE_ENV: !Ref Environment

Resources:
  # ==========================================
  # DynamoDB Table (Simplified)
  # ==========================================
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub BayonCoAgent-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BayonCoAgent

  # ==========================================
  # S3 Storage Bucket (Simplified)
  # ==========================================
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bayon-coagent-storage-${Environment}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: BayonCoAgent

  # ==========================================
  # IAM Role for Lambda Functions
  # ==========================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt DynamoDBTable.Arn
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub ${StorageBucket.Arn}/*

  # ==========================================
  # Test Lambda Function with ARM64 and Provisioned Concurrency
  # ==========================================
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub bayon-coagent-test-${Environment}
      CodeUri: src/lambda/
      Handler: test-functions.handler
      Runtime: nodejs22.x
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrency: !If [IsProduction, 2, 0]
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
          S3_BUCKET_NAME: !Ref StorageBucket
      Tags:
        Environment: !Ref Environment
        Application: BayonCoAgent
        Function: Test

Outputs:
  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDBTableName

  StorageBucketName:
    Description: Name of the S3 storage bucket
    Value: !Ref StorageBucket
    Export:
      Name: !Sub ${AWS::StackName}-StorageBucketName

  TestFunctionArn:
    Description: ARN of the test Lambda function
    Value: !GetAtt TestFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TestFunctionArn
