/**
 * ROI Tracker Usage Examples
 * 
 * Examples demonstrating how to use the ROI tracking system
 * to track business outcomes and calculate content ROI.
 */

import { createROITracker, BusinessOutcome, OutcomeType } from './roi-tracker';

/**
 * Example 1: Track a lead generation outcome
 */
async function trackLeadGeneration() {
    const roiTracker = createROITracker();

    const outcome: BusinessOutcome = {
        id: `outcome-${Date.now()}`,
        contentId: 'blog-post-123',
        strandId: 'content-generator-strand',
        userId: 'user-456',
        type: 'lead-generated',
        value: 0, // No immediate monetary value
        description: 'User filled out contact form after reading blog post',
        occurredAt: new Date().toISOString(),
        metadata: {
            contentType: 'blog-post',
            source: 'organic-search',
            leadQuality: 'high',
            creationCost: 5.50, // Cost to generate the blog post
            distributionCost: 0, // No paid distribution
        },
    };

    await roiTracker.trackOutcome(outcome);
    console.log('Lead generation outcome tracked');
}

/**
 * Example 2: Track a sale closure
 */
async function trackSaleClosure() {
    const roiTracker = createROITracker();

    const outcome: BusinessOutcome = {
        id: `outcome-${Date.now()}`,
        contentId: 'listing-description-789',
        strandId: 'listing-description-strand',
        userId: 'user-456',
        type: 'sale-closed',
        value: 15000, // Commission earned
        description: 'Property sold - listing description generated by AI',
        occurredAt: new Date().toISOString(),
        metadata: {
            contentType: 'listing-description',
            propertyValue: 500000,
            commissionRate: 0.03,
            creationCost: 3.25,
            distributionCost: 200, // MLS listing fees
        },
    };

    await roiTracker.trackOutcome(outcome);
    console.log('Sale closure outcome tracked');
}

/**
 * Example 3: Track engagement metrics
 */
async function trackEngagement() {
    const roiTracker = createROITracker();

    const outcomes: BusinessOutcome[] = [
        {
            id: `outcome-${Date.now()}-1`,
            contentId: 'social-post-456',
            strandId: 'social-media-strand',
            userId: 'user-456',
            type: 'property-viewed',
            value: 0,
            description: 'User viewed property listing from social media post',
            occurredAt: new Date().toISOString(),
            metadata: {
                contentType: 'social-media-post',
                platform: 'instagram',
                creationCost: 2.00,
                distributionCost: 0,
            },
        },
        {
            id: `outcome-${Date.now()}-2`,
            contentId: 'social-post-456',
            strandId: 'social-media-strand',
            userId: 'user-456',
            type: 'engagement',
            value: 0,
            description: 'User clicked link in social media post',
            occurredAt: new Date().toISOString(),
            metadata: {
                contentType: 'social-media-post',
                platform: 'instagram',
                engagementType: 'link-click',
            },
        },
    ];

    for (const outcome of outcomes) {
        await roiTracker.trackOutcome(outcome);
    }

    console.log('Engagement outcomes tracked');
}

/**
 * Example 4: Calculate ROI for specific content
 */
async function calculateContentROI() {
    const roiTracker = createROITracker();

    const contentId = 'blog-post-123';
    const userId = 'user-456';

    const roi = await roiTracker.calculateROI(contentId, userId);

    if (roi) {
        console.log('ROI Calculation:');
        console.log(`  Investment: $${roi.investment.toFixed(2)}`);
        console.log(`  Return: $${roi.return.toFixed(2)}`);
        console.log(`  Profit: $${roi.profit.toFixed(2)}`);
        console.log(`  ROI: ${roi.roiPercentage.toFixed(1)}%`);
        console.log(`  Payback Period: ${roi.paybackPeriod} days`);
    } else {
        console.log('No ROI data available for this content');
    }
}

/**
 * Example 5: Get content performance metrics
 */
async function getContentPerformance() {
    const roiTracker = createROITracker();

    const contentId = 'listing-description-789';
    const userId = 'user-456';

    const performance = await roiTracker.getContentPerformance(contentId, userId);

    if (performance) {
        console.log('Content Performance:');
        console.log(`  Content Type: ${performance.contentType}`);
        console.log(`  Views: ${performance.views}`);
        console.log(`  Clicks: ${performance.clicks}`);
        console.log(`  Leads: ${performance.leads}`);
        console.log(`  Conversions: ${performance.conversions}`);
        console.log(`  Revenue: $${performance.revenue.toFixed(2)}`);
        console.log(`  Total Cost: $${performance.totalCost.toFixed(2)}`);
        console.log(`  ROI: ${performance.roi.toFixed(1)}%`);
    } else {
        console.log('No performance data available');
    }
}

/**
 * Example 6: Generate comprehensive ROI report
 */
async function generateROIReport() {
    const roiTracker = createROITracker();

    const report = await roiTracker.generateReport({
        userId: 'user-456',
        startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // Last 30 days
        endDate: new Date().toISOString(),
    });

    console.log('ROI Report:');
    console.log(`  Title: ${report.title}`);
    console.log(`  Period: ${report.period.start} to ${report.period.end}`);
    console.log(`  Total Investment: $${report.totalInvestment.toFixed(2)}`);
    console.log(`  Total Return: $${report.totalReturn.toFixed(2)}`);
    console.log(`  Overall ROI: ${report.overallROI.toFixed(1)}%`);
    console.log('\nTop Performers:');
    report.topPerformers.slice(0, 5).forEach((content, index) => {
        console.log(`  ${index + 1}. ${content.contentType} - ROI: ${content.roi.toFixed(1)}%`);
    });
    console.log('\nInsights:');
    report.insights.forEach(insight => {
        console.log(`  - ${insight}`);
    });
    console.log('\nRecommendations:');
    report.recommendations.forEach(rec => {
        console.log(`  - ${rec}`);
    });
}

/**
 * Example 7: Correlate strand performance with content outcomes
 */
async function correlateStrandPerformance() {
    const roiTracker = createROITracker();

    const correlation = await roiTracker.correlatePerformance(
        'user-456',
        'content-generator-strand',
        '30d'
    );

    console.log('Strand Performance Correlation:');
    console.log(`  Correlation Score: ${(correlation.correlation * 100).toFixed(1)}%`);
    console.log('\nInsights:');
    correlation.insights.forEach(insight => {
        console.log(`  - ${insight}`);
    });
}

/**
 * Example 8: Track multiple outcomes for a campaign
 */
async function trackCampaignOutcomes() {
    const roiTracker = createROITracker();

    const campaignContentId = 'email-campaign-001';
    const userId = 'user-456';
    const strandId = 'email-campaign-strand';

    // Track various outcomes throughout the campaign
    const outcomes: BusinessOutcome[] = [
        // Week 1: Initial engagement
        {
            id: `outcome-${Date.now()}-1`,
            contentId: campaignContentId,
            strandId,
            userId,
            type: 'property-viewed',
            value: 0,
            description: 'Email opened and property viewed',
            occurredAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            metadata: {
                contentType: 'email-campaign',
                campaignName: 'Spring Listings 2024',
                creationCost: 8.50,
                distributionCost: 50, // Email service costs
            },
        },
        // Week 2: Lead generation
        {
            id: `outcome-${Date.now()}-2`,
            contentId: campaignContentId,
            strandId,
            userId,
            type: 'lead-generated',
            value: 0,
            description: 'Recipient requested more information',
            occurredAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            metadata: {
                contentType: 'email-campaign',
                leadSource: 'email-reply',
            },
        },
        // Week 3: Appointment scheduled
        {
            id: `outcome-${Date.now()}-3`,
            contentId: campaignContentId,
            strandId,
            userId,
            type: 'appointment-scheduled',
            value: 0,
            description: 'Property showing scheduled',
            occurredAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            metadata: {
                contentType: 'email-campaign',
                appointmentType: 'property-showing',
            },
        },
        // Week 4: Sale closed
        {
            id: `outcome-${Date.now()}-4`,
            contentId: campaignContentId,
            strandId,
            userId,
            type: 'sale-closed',
            value: 12000, // Commission
            description: 'Property sold to campaign lead',
            occurredAt: new Date().toISOString(),
            metadata: {
                contentType: 'email-campaign',
                propertyValue: 400000,
                commissionRate: 0.03,
            },
        },
    ];

    for (const outcome of outcomes) {
        await roiTracker.trackOutcome(outcome);
    }

    // Calculate final ROI
    const roi = await roiTracker.calculateROI(campaignContentId, userId);

    if (roi) {
        console.log('Campaign ROI:');
        console.log(`  Investment: $${roi.investment.toFixed(2)}`);
        console.log(`  Return: $${roi.return.toFixed(2)}`);
        console.log(`  ROI: ${roi.roiPercentage.toFixed(1)}%`);
        console.log(`  Payback Period: ${roi.paybackPeriod} days`);
    }
}

/**
 * Example 9: Filter ROI report by content type
 */
async function generateContentTypeReport() {
    const roiTracker = createROITracker();

    const report = await roiTracker.generateReport({
        userId: 'user-456',
        contentType: 'blog-post',
        minROI: 50, // Only show content with >50% ROI
        startDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
        endDate: new Date().toISOString(),
    });

    console.log('Blog Post ROI Report:');
    console.log(`  Total Investment: $${report.totalInvestment.toFixed(2)}`);
    console.log(`  Total Return: $${report.totalReturn.toFixed(2)}`);
    console.log(`  Overall ROI: ${report.overallROI.toFixed(1)}%`);
    console.log(`  Number of Posts: ${report.topPerformers.length + report.bottomPerformers.length}`);
}

/**
 * Example 10: Real-time ROI tracking dashboard
 */
async function trackRealTimeROI() {
    const roiTracker = createROITracker();

    // Simulate tracking outcomes as they happen
    const contentId = 'social-campaign-202';
    const userId = 'user-456';

    // Track initial creation
    console.log('Content created - tracking costs...');
    await roiTracker.trackOutcome({
        id: `outcome-${Date.now()}`,
        contentId,
        strandId: 'social-media-strand',
        userId,
        type: 'engagement',
        value: 0,
        description: 'Content published',
        occurredAt: new Date().toISOString(),
        metadata: {
            contentType: 'social-media-post',
            creationCost: 3.00,
            distributionCost: 25, // Paid promotion
        },
    });

    // Check performance after 1 hour
    setTimeout(async () => {
        const performance = await roiTracker.getContentPerformance(contentId, userId);
        console.log('1 hour update:', performance);
    }, 3600000);

    // Check ROI after 24 hours
    setTimeout(async () => {
        const roi = await roiTracker.calculateROI(contentId, userId);
        console.log('24 hour ROI:', roi);
    }, 86400000);
}

// Export examples for testing
export {
    trackLeadGeneration,
    trackSaleClosure,
    trackEngagement,
    calculateContentROI,
    getContentPerformance,
    generateROIReport,
    correlateStrandPerformance,
    trackCampaignOutcomes,
    generateContentTypeReport,
    trackRealTimeROI,
};
