
'use client';

import { useMemo, useActionState, useEffect } from 'react';
import { useFormStatus } from 'react-dom';
import { PageHeader } from '@/components/page-header';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Loader2,
  Sparkles,
  Target,
  ArrowRight,
  BookText,
  ShieldCheck,
  Users,
} from 'lucide-react';
import { useUser, useFirestore, useDoc, useCollection, useMemoFirebase, addDocumentNonBlocking } from '@/firebase';
import { doc, collection, query, orderBy, limit } from 'firebase/firestore';
import type { BrandAudit, Competitor, MarketingPlan as MarketingPlanType } from '@/lib/types';
import { generateMarketingPlanAction } from '@/app/actions';
import { toast } from '@/hooks/use-toast';
import Link from 'next/link';

type GeneratePlanState = {
  message: string;
  data: MarketingPlanType | null;
  errors: any;
};

const initialPlanState: GeneratePlanState = {
  message: '',
  data: null,
  errors: {},
};

function GeneratePlanButton({ disabled }: { disabled?: boolean }) {
  const { pending } = useFormStatus();
  return (
    <Button
      type="submit"
      variant={pending ? 'shimmer' : 'ai'}
      disabled={pending || disabled}
      size="lg"
    >
      {pending ? (
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
      ) : (
        <Sparkles className="mr-2 h-4 w-4" />
      )}
      {pending ? 'Generating Plan...' : 'Generate My Marketing Plan'}
    </Button>
  );
}

const toolIcons: { [key: string]: React.ReactNode } = {
  'Content Engine': <BookText className="mr-2 h-4 w-4" />,
  'Brand Audit': <ShieldCheck className="mr-2 h-4 w-4" />,
  'Competitive Analysis': <Users className="mr-2 h-4 w-4" />,
};

export default function MarketingPlanPage() {
  const { user, isUserLoading } = useUser();
  const firestore = useFirestore();

  const [state, formAction] = useActionState(generateMarketingPlanAction, initialPlanState);

  const brandAuditRef = useMemoFirebase(() => {
    if (!firestore || !user) return null;
    return doc(firestore, `users/${user.uid}/brandAudits/main`);
  }, [firestore, user]);

  const competitorsRef = useMemoFirebase(() => {
    if (!firestore || !user) return null;
    return collection(firestore, `users/${user.uid}/competitors`);
  }, [firestore, user]);

  const latestPlanRef = useMemoFirebase(() => {
    if (!firestore || !user) return null;
    return query(
      collection(firestore, `users/${user.uid}/marketingPlans`),
      orderBy('createdAt', 'desc'),
      limit(1)
    );
  }, [firestore, user]);

  const { data: brandAuditData, isLoading: isAuditLoading } = useDoc<BrandAudit>(brandAuditRef);
  const { data: competitorsData, isLoading: areCompetitorsLoading } = useCollection<Competitor>(competitorsRef);
  const { data: latestPlanData, isLoading: isPlanLoading } = useCollection<MarketingPlanType>(latestPlanRef);

  const isDataReady = !isAuditLoading && !areCompetitorsLoading && !!brandAuditData && !!competitorsData;
  const displayPlan = state.data ?? (latestPlanData && latestPlanData[0]);

  useEffect(() => {
    if (state.message === 'success' && state.data) {
        if (user?.uid) {
             addDocumentNonBlocking(`users/${user.uid}/marketingPlans`, state.data);
             toast({
                 title: 'Plan Generated!',
                 description: 'Your new personalized marketing plan is ready.',
             });
        }
    } else if (state.message && state.message !== 'success') {
      toast({
        variant: 'destructive',
        title: 'Failed to Generate Plan',
        description: state.message,
      });
    }
  }, [state, user?.uid]);

  return (
    <div className="animate-fade-in-up space-y-8">
      <PageHeader
        title="Your AI Marketing Plan"
        description="A personalized, actionable plan generated by AI based on your current brand and competitor data."
      />

      <Card className="text-center">
        <CardHeader>
          <CardTitle className="font-headline text-3xl">Ready to Grow Your Brand?</CardTitle>
          <CardDescription>
            Click the button below to have our AI analyze your Brand Audit and Competitive Analysis data. It will create a tailored 3-step plan to address your biggest marketing opportunities.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form action={formAction}>
            <input type="hidden" name="userId" value={user?.uid || ''} />
            <input type="hidden" name="brandAudit" value={JSON.stringify(brandAuditData || { results: [] })} />
            <input type="hidden" name="competitors" value={JSON.stringify(competitorsData || [])} />
            <GeneratePlanButton disabled={!isDataReady} />
            {!isDataReady && (
              <p className="text-sm text-muted-foreground mt-2">
                Waiting for Brand Audit and Competitor data to load...
              </p>
            )}
          </form>
        </CardContent>
      </Card>

      {isPlanLoading && !displayPlan && (
         <Card>
            <CardHeader>
                <CardTitle className="font-headline">Your Action Plan</CardTitle>
                <CardDescription>Here are your personalized next steps.</CardDescription>
            </CardHeader>
            <CardContent className="flex items-center justify-center h-48">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="ml-4 text-muted-foreground">Loading your latest plan...</p>
            </CardContent>
        </Card>
      )}

      {displayPlan && (
        <Card>
          <CardHeader>
            <CardTitle className="font-headline">Your Action Plan</CardTitle>
            <CardDescription>
              Here are your personalized next steps, generated on {new Date(displayPlan.createdAt).toLocaleDateString()}.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-6">
              {displayPlan.plan.map((item, index) => (
                <li
                  key={index}
                  className="flex items-start gap-4 p-4 rounded-lg border bg-secondary/30"
                >
                  <div className="flex-shrink-0 font-bold text-primary text-3xl font-headline">
                    {index + 1}
                  </div>
                  <div className="flex-grow">
                    <h3 className="font-semibold text-lg">{item.task}</h3>
                    <p className="text-sm text-muted-foreground mt-1 mb-3">{item.rationale}</p>
                    <Button asChild size="sm">
                      <Link href={item.toolLink}>
                        {toolIcons[item.tool] || <Target className="mr-2 h-4 w-4" />}
                        Use {item.tool}
                        <ArrowRight className="ml-2 h-4 w-4" />
                      </Link>
                    </Button>
                  </div>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {!isPlanLoading && !displayPlan && (
         <Card className="text-center py-12">
            <CardContent>
                <Target className="mx-auto h-12 w-12 text-muted-foreground" />
                <h3 className="mt-4 text-lg font-medium">No Plan Generated Yet</h3>
                <p className="mt-1 text-sm text-muted-foreground">
                    Click the button above to create your first personalized marketing plan.
                </p>
            </CardContent>
        </Card>
      )}
    </div>
  );
}
