name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
      docs: ${{ steps.filter.outputs.docs }}
      dependencies: ${{ steps.filter.outputs.dependencies }}
      config: ${{ steps.filter.outputs.config }}
      infrastructure: ${{ steps.filter.outputs.infrastructure }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**/*.{ts,tsx,js,jsx}'
              - 'public/**'
            docs:
              - 'docs/**'
              - '*.md'
            dependencies:
              - 'package.json'
              - 'package-lock.json'
            config:
              - 'tsconfig.json'
              - 'next.config.ts'
              - 'jest.config.js'
              - 'tailwind.config.ts'
              - 'postcss.config.mjs'
            infrastructure:
              - 'template*.yaml'
              - 'samconfig.toml'
              - 'infrastructure/**'

  quality:
    name: Quality & Security
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.code == 'true' || needs.changes.outputs.config == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: |
          npm run lint &
          npm run typecheck &
          npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}" &
          wait

      - name: Run security scans
        run: |
          npm audit --audit-level=high

      - name: Scan for secrets
        run: |
          if git log --all -p | grep -E "AKIA[0-9A-Z]{16}" > /dev/null; then
            echo "::error::AWS access keys detected!"
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.code == 'true' || needs.changes.outputs.dependencies == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: env.CODECOV_TOKEN != ''
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [changes, quality, test]
    if: always() && needs.changes.outputs.code == 'true' || needs.changes.outputs.dependencies == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Check bundle size
        run: |
          BUILD_SIZE=$(du -sh .next | cut -f1)
          echo "Build size: $BUILD_SIZE"

  validate-infrastructure:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.infrastructure == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate SAM templates
        run: |
          sam validate --lint
          pip install cfn-lint
          cfn-lint template.yaml

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [changes, quality, test, build, validate-infrastructure]
    if: always()
    steps:
      - name: Check results
        run: |
          echo "## CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Quality & Security | ${{ needs.quality.result == 'success' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Tests | ${{ needs.test.result == 'success' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result == 'success' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Infrastructure | ${{ needs.validate-infrastructure.result == 'success' && '✅' || needs.validate-infrastructure.result == 'skipped' && '⬜' || '❌' }} |" >> $GITHUB_STEP_SUMMARY

      - name: Fail if critical jobs failed
        if: needs.quality.result == 'failure' || needs.test.result == 'failure' || needs.build.result == 'failure' || needs.validate-infrastructure.result == 'failure'
        run: exit 1
