name: Deploy

on:
  push:
    branches: [develop]
    tags: ["rc-*", "v*"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options: [development, staging, production]
      skip-tests:
        description: "Skip smoke tests"
        type: boolean
        default: false

env:
  AWS_REGION: us-west-2

jobs:
  determine-environment:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      stack-name: ${{ steps.env.outputs.stack-name }}
      branch: ${{ steps.env.outputs.branch }}
      requires-approval: ${{ steps.env.outputs.requires-approval }}
    steps:
      - name: Determine environment
        id: env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ENV="${{ inputs.environment }}"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            ENV="development"
          elif [[ "${{ github.ref }}" == refs/tags/rc-* ]]; then
            ENV="staging"
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            ENV="production"
          else
            echo "Unknown deployment trigger"
            exit 1
          fi

          echo "environment=$ENV" >> $GITHUB_OUTPUT
          echo "stack-name=bayon-coagent-$ENV" >> $GITHUB_OUTPUT

          case "$ENV" in
            development)
              echo "branch=develop" >> $GITHUB_OUTPUT
              echo "requires-approval=false" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "branch=staging" >> $GITHUB_OUTPUT
              echo "requires-approval=true" >> $GITHUB_OUTPUT
              ;;
            production)
              echo "branch=main" >> $GITHUB_OUTPUT
              echo "requires-approval=true" >> $GITHUB_OUTPUT
              ;;
          esac

  approval:
    name: Deployment Approval
    runs-on: ubuntu-latest
    needs: determine-environment
    if: needs.determine-environment.outputs.requires-approval == 'true'
    environment:
      name: ${{ needs.determine-environment.outputs.environment }}
    steps:
      - name: Approval granted
        run: echo "✅ Deployment approved for ${{ needs.determine-environment.outputs.environment }}"

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: [determine-environment, approval]
    if: always() && needs.determine-environment.result == 'success' && (needs.approval.result == 'success' || needs.approval.result == 'skipped')
    outputs:
      stack-outputs: ${{ steps.outputs.outputs.outputs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS credentials variables
        id: aws-creds
        run: |
          ENV="${{ needs.determine-environment.outputs.environment }}"
          case "$ENV" in
            development)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" >> $GITHUB_OUTPUT
              ;;
            production)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ steps.aws-creds.outputs.access-key-id }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.secret-access-key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Deploy SAM stack
        run: |
          sam deploy \
            --config-env ${{ needs.determine-environment.outputs.environment }} \
            --parameter-overrides Environment=${{ needs.determine-environment.outputs.environment }} \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset

      - name: Get stack outputs
        id: outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name ${{ needs.determine-environment.outputs.stack-name }} \
            --region ${{ env.AWS_REGION }} \
            --query 'Stacks[0].Outputs' \
            --output json > stack-outputs.json

          OUTPUTS=$(cat stack-outputs.json | jq -c .)
          echo "outputs=$OUTPUTS" >> $GITHUB_OUTPUT

      - name: Upload stack outputs
        uses: actions/upload-artifact@v4
        with:
          name: stack-outputs-${{ needs.determine-environment.outputs.environment }}
          path: stack-outputs.json
          retention-days: 30

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [determine-environment, deploy-infrastructure]
    outputs:
      deployment-url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS credentials variables
        id: aws-creds
        run: |
          ENV="${{ needs.determine-environment.outputs.environment }}"
          case "$ENV" in
            development)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" >> $GITHUB_OUTPUT
              ;;
            production)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ steps.aws-creds.outputs.access-key-id }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.secret-access-key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download stack outputs
        uses: actions/download-artifact@v4
        with:
          name: stack-outputs-${{ needs.determine-environment.outputs.environment }}

      - name: Extract environment variables
        id: env-vars
        run: |
          COGNITO_USER_POOL_ID=$(jq -r '.[] | select(.OutputKey=="CognitoUserPoolId") | .OutputValue' stack-outputs.json)
          COGNITO_CLIENT_ID=$(jq -r '.[] | select(.OutputKey=="CognitoClientId") | .OutputValue' stack-outputs.json)
          DYNAMODB_TABLE_NAME=$(jq -r '.[] | select(.OutputKey=="DynamoDBTableName") | .OutputValue' stack-outputs.json)
          S3_BUCKET_NAME=$(jq -r '.[] | select(.OutputKey=="S3BucketName") | .OutputValue' stack-outputs.json)

          echo "cognito_user_pool_id=$COGNITO_USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "cognito_client_id=$COGNITO_CLIENT_ID" >> $GITHUB_OUTPUT
          echo "dynamodb_table_name=$DYNAMODB_TABLE_NAME" >> $GITHUB_OUTPUT
          echo "s3_bucket_name=$S3_BUCKET_NAME" >> $GITHUB_OUTPUT

      - name: Deploy to Amplify
        id: deploy
        run: |
          APP_ID=$(aws amplify list-apps \
            --region ${{ env.AWS_REGION }} \
            --query "apps[?name=='bayon-coagent-${{ needs.determine-environment.outputs.environment }}'].appId" \
            --output text)

          if [ -z "$APP_ID" ]; then
            echo "❌ Amplify app not found"
            exit 1
          fi

          # Update environment variables
          aws amplify update-app \
            --app-id $APP_ID \
            --region ${{ env.AWS_REGION }} \
            --environment-variables \
              NODE_ENV=${{ needs.determine-environment.outputs.environment }} \
              AWS_REGION=${{ env.AWS_REGION }} \
              COGNITO_USER_POOL_ID=${{ steps.env-vars.outputs.cognito_user_pool_id }} \
              COGNITO_CLIENT_ID=${{ steps.env-vars.outputs.cognito_client_id }} \
              DYNAMODB_TABLE_NAME=${{ steps.env-vars.outputs.dynamodb_table_name }} \
              S3_BUCKET_NAME=${{ steps.env-vars.outputs.s3_bucket_name }}

          # Trigger deployment
          JOB_ID=$(aws amplify start-job \
            --app-id $APP_ID \
            --branch-name ${{ needs.determine-environment.outputs.branch }} \
            --job-type RELEASE \
            --region ${{ env.AWS_REGION }} \
            --query 'jobSummary.jobId' \
            --output text)

          # Monitor deployment
          while true; do
            STATUS=$(aws amplify get-job \
              --app-id $APP_ID \
              --branch-name ${{ needs.determine-environment.outputs.branch }} \
              --job-id $JOB_ID \
              --region ${{ env.AWS_REGION }} \
              --query 'job.summary.status' \
              --output text)
            
            if [ "$STATUS" = "SUCCEED" ]; then
              break
            elif [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "CANCELLED" ]; then
              echo "❌ Deployment failed: $STATUS"
              exit 1
            fi
            sleep 30
          done

          # Get deployment URL
          DOMAIN=$(aws amplify get-app \
            --app-id $APP_ID \
            --region ${{ env.AWS_REGION }} \
            --query 'app.defaultDomain' \
            --output text)

          URL="https://${{ needs.determine-environment.outputs.branch }}.${DOMAIN}"
          echo "url=$URL" >> $GITHUB_OUTPUT

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: [determine-environment, deploy-frontend]
    if: ${{ !inputs.skip-tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set AWS credentials variables
        id: aws-creds
        run: |
          ENV="${{ needs.determine-environment.outputs.environment }}"
          case "$ENV" in
            development)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_OUTPUT
              ;;
            staging)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" >> $GITHUB_OUTPUT
              ;;
            production)
              echo "access-key-id=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_OUTPUT
              echo "secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ steps.aws-creds.outputs.access-key-id }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.secret-access-key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run smoke tests
        run: |
          echo "Running smoke tests against ${{ needs.deploy-frontend.outputs.deployment-url }}"

          # Basic health check
          curl -f ${{ needs.deploy-frontend.outputs.deployment-url }} || exit 1

          # Test authentication endpoint
          curl -f ${{ needs.deploy-frontend.outputs.deployment-url }}/api/auth/session || echo "Auth endpoint check"

          echo "✅ Smoke tests passed"

  performance-test:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: [determine-environment, deploy-frontend]
    if: needs.determine-environment.outputs.environment != 'development'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse audit
        run: |
          lighthouse ${{ needs.deploy-frontend.outputs.deployment-url }} \
            --output=json \
            --output-path=lighthouse-results.json \
            --chrome-flags="--headless --no-sandbox"

          PERFORMANCE=$(jq '.categories.performance.score * 100' lighthouse-results.json)
          echo "Performance score: $PERFORMANCE"

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results-${{ needs.determine-environment.outputs.environment }}
          path: lighthouse-results.json
          retention-days: 30

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      [determine-environment, deploy-frontend, smoke-tests, performance-test]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine status
        id: status
        run: |
          if [ "${{ needs.deploy-frontend.result }}" = "success" ] && [ "${{ needs.smoke-tests.result }}" != "failure" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "message=Deployment completed successfully" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "message=Deployment failed" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack notification
        if: env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS_EMOJI="${{ steps.status.outputs.status == 'success' && '✅' || '❌' }}"

          curl -X POST "$SLACK_WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d "{
              \"text\": \"$STATUS_EMOJI Deployment to ${{ needs.determine-environment.outputs.environment }}\",
              \"attachments\": [{
                \"color\": \"${{ steps.status.outputs.status == 'success' && 'good' || 'danger' }}\",
                \"fields\": [
                  {
                    \"title\": \"Environment\",
                    \"value\": \"${{ needs.determine-environment.outputs.environment }}\",
                    \"short\": true
                  },
                  {
                    \"title\": \"Status\",
                    \"value\": \"${{ steps.status.outputs.message }}\",
                    \"short\": true
                  },
                  {
                    \"title\": \"URL\",
                    \"value\": \"${{ needs.deploy-frontend.outputs.deployment-url }}\",
                    \"short\": false
                  }
                ]
              }]
            }"
