name: Test Fix

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - ".github/workflows/**"
            - "jest.config.js"
            - "src/__tests__/**"

jobs:
    test-basic:
        name: Test Basic Setup
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run basic tests
              run: npm run test -- --testPathPattern=basic.test.ts

            - name: Run lint
              run: npm run lint

            - name: Run typecheck
              run: npm run typecheck

            - name: Test build
              run: npm run build
