name: Verify Secrets Configuration

on:
    workflow_dispatch:

jobs:
    verify-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Check AWS Dev Credentials
              run: |
                  if [ -z "${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" ]; then
                    echo "❌ AWS_ACCESS_KEY_ID_DEV not configured"
                    exit 1
                  fi
                  echo "✅ AWS_ACCESS_KEY_ID_DEV configured"

            - name: Check AWS Dev Secret Key
              run: |
                  if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" ]; then
                    echo "❌ AWS_SECRET_ACCESS_KEY_DEV not configured"
                    exit 1
                  fi
                  echo "✅ AWS_SECRET_ACCESS_KEY_DEV configured"

            - name: Check AWS Dev Region
              run: |
                  if [ -z "${{ secrets.AWS_REGION_DEV }}" ]; then
                    echo "⚠️  AWS_REGION_DEV not configured (will use default)"
                  else
                    echo "✅ AWS_REGION_DEV configured"
                  fi

            - name: Check AWS Staging Credentials
              run: |
                  if [ -z "${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" ]; then
                    echo "❌ AWS_ACCESS_KEY_ID_STAGING not configured"
                    exit 1
                  fi
                  echo "✅ AWS_ACCESS_KEY_ID_STAGING configured"

            - name: Check AWS Staging Secret Key
              run: |
                  if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" ]; then
                    echo "❌ AWS_SECRET_ACCESS_KEY_STAGING not configured"
                    exit 1
                  fi
                  echo "✅ AWS_SECRET_ACCESS_KEY_STAGING configured"

            - name: Check AWS Staging Region
              run: |
                  if [ -z "${{ secrets.AWS_REGION_STAGING }}" ]; then
                    echo "⚠️  AWS_REGION_STAGING not configured (will use default)"
                  else
                    echo "✅ AWS_REGION_STAGING configured"
                  fi

            - name: Check AWS Prod Credentials
              run: |
                  if [ -z "${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" ]; then
                    echo "❌ AWS_ACCESS_KEY_ID_PROD not configured"
                    exit 1
                  fi
                  echo "✅ AWS_ACCESS_KEY_ID_PROD configured"

            - name: Check AWS Prod Secret Key
              run: |
                  if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" ]; then
                    echo "❌ AWS_SECRET_ACCESS_KEY_PROD not configured"
                    exit 1
                  fi
                  echo "✅ AWS_SECRET_ACCESS_KEY_PROD configured"

            - name: Check AWS Prod Region
              run: |
                  if [ -z "${{ secrets.AWS_REGION_PROD }}" ]; then
                    echo "⚠️  AWS_REGION_PROD not configured (will use default)"
                  else
                    echo "✅ AWS_REGION_PROD configured"
                  fi

            - name: Check Slack Webhook
              run: |
                  if [ -z "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
                    echo "❌ SLACK_WEBHOOK_URL not configured"
                    exit 1
                  fi
                  echo "✅ SLACK_WEBHOOK_URL configured"

            - name: Check Slack Channels
              run: |
                  if [ -z "${{ secrets.SLACK_CHANNEL_DEVOPS }}" ]; then
                    echo "⚠️  SLACK_CHANNEL_DEVOPS not configured (will use default)"
                  else
                    echo "✅ SLACK_CHANNEL_DEVOPS configured"
                  fi
                  if [ -z "${{ secrets.SLACK_CHANNEL_TEAM }}" ]; then
                    echo "⚠️  SLACK_CHANNEL_TEAM not configured (will use default)"
                  else
                    echo "✅ SLACK_CHANNEL_TEAM configured"
                  fi

            - name: Check Snyk Token
              run: |
                  if [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
                    echo "❌ SNYK_TOKEN not configured"
                    exit 1
                  fi
                  echo "✅ SNYK_TOKEN configured"

            - name: Check Codecov Token
              run: |
                  if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
                    echo "❌ CODECOV_TOKEN not configured"
                    exit 1
                  fi
                  echo "✅ CODECOV_TOKEN configured"

            - name: Check Optional Secrets
              run: |
                  if [ -z "${{ secrets.PAGERDUTY_INTEGRATION_KEY }}" ]; then
                    echo "ℹ️  PAGERDUTY_INTEGRATION_KEY not configured (optional)"
                  else
                    echo "✅ PAGERDUTY_INTEGRATION_KEY configured"
                  fi
                  if [ -z "${{ secrets.DATADOG_API_KEY }}" ]; then
                    echo "ℹ️  DATADOG_API_KEY not configured (optional)"
                  else
                    echo "✅ DATADOG_API_KEY configured"
                  fi

            - name: All Required Secrets Verified
              run: |
                  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
                  echo "✅ All required secrets are configured!"
                  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
