'use client';

import { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { StandardSkeleton } from '@/components/standard/skeleton';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Download, Sparkles } from 'lucide-react';
import { useUser } from '@/aws/auth';
import { useToast } from '@/hooks/use-toast';
import { getReportByIdAction } from '@/app/actions';

interface TrainingPlan {
    id: string;
    topic: string;
    report: string;
    createdAt: number;
}

export default function TrainingPlanViewPage() {
    const params = useParams();
    const router = useRouter();
    const { user } = useUser();
    const { toast } = useToast();
    const [plan, setPlan] = useState<TrainingPlan | null>(null);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        if (!user || !params.id) {
            setIsLoading(false);
            return;
        }

        const fetchPlan = async () => {
            try {
                const result = await getReportByIdAction(params.id as string, user.id);

                if (result.errors) {
                    console.error('Failed to fetch training plan:', result.errors);
                    toast({
                        title: 'Error',
                        description: result.errors.join(', '),
                        variant: 'destructive',
                    });
                } else if (result.data) {
                    setPlan({
                        id: result.data.id,
                        topic: result.data.topic,
                        report: result.data.report,
                        createdAt: result.data.createdAt,
                    });
                }
            } catch (error) {
                console.error('Failed to fetch training plan:', error);
                toast({
                    title: 'Error',
                    description: 'Failed to load training plan.',
                    variant: 'destructive',
                });
            } finally {
                setIsLoading(false);
            }
        };

        fetchPlan();
    }, [user, params.id, toast]);

    const handleDownload = () => {
        if (!plan) return;

        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Training Plan - ${plan.topic}</title>
    <style>
        body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        h3 { color: #1a1a1a; margin-top: 24px; margin-bottom: 12px; font-size: 1.25rem; font-weight: 600; }
        h4 { color: #333; margin-top: 16px; margin-bottom: 8px; font-weight: 600; }
        p { margin-top: 8px; color: #4a4a4a; }
        ul, ol { margin-left: 24px; margin-top: 8px; }
        li { margin-top: 8px; }
        strong { font-weight: 600; color: #1a1a1a; }
        .header { border-bottom: 2px solid #e5e5e5; padding-bottom: 16px; margin-bottom: 24px; }
        .challenge { background: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Your Personalized Training Plan</h1>
        <p>Generated by Bayon Coagent</p>
    </div>
    <div class="challenge">
        <strong>Challenge:</strong> ${plan.topic}
    </div>
    ${plan.report}
</body>
</html>
        `;

        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `training-plan-${plan.id}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        toast({
            title: 'Downloaded',
            description: 'Training plan downloaded as HTML file.',
        });
    };

    if (isLoading) {
        return <StandardSkeleton variant="content" />;
    }

    if (!plan) {
        return (
            <div className="space-y-6">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" onClick={() => router.back()}>
                        <ArrowLeft className="h-4 w-4 mr-2" />
                        Back
                    </Button>
                </div>
                <Card>
                    <CardContent className="p-8 text-center">
                        <p className="text-muted-foreground">Training plan not found.</p>
                    </CardContent>
                </Card>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" onClick={() => router.back()}>
                        <ArrowLeft className="h-4 w-4 mr-2" />
                        Back
                    </Button>
                </div>
                <Button onClick={handleDownload} variant="outline">
                    <Download className="h-4 w-4 mr-2" />
                    Download
                </Button>
            </div>

            <Card>
                <CardHeader>
                    <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                            <Sparkles className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                            <CardTitle className="font-headline text-xl">Your Training Plan</CardTitle>
                            <p className="text-sm text-muted-foreground">
                                Created {new Date(plan.createdAt).toLocaleDateString()}
                            </p>
                        </div>
                    </div>
                </CardHeader>
                <CardContent>
                    <div className="space-y-4">
                        <div className="p-4 bg-muted/50 rounded-lg">
                            <h4 className="font-headline font-semibold mb-2">Challenge:</h4>
                            <p className="text-sm">{plan.topic}</p>
                        </div>
                        <div
                            className="prose prose-sm md:prose-base max-w-none text-foreground/80 dark:prose-invert prose-headings:text-foreground prose-a:text-primary prose-strong:text-foreground"
                            dangerouslySetInnerHTML={{ __html: plan.report }}
                        />
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}