'use client';

import { useState, useMemo, useCallback } from 'react';
import { AnimatedTabs as Tabs, AnimatedTabsContent as TabsContent, AnimatedTabsList as TabsList, AnimatedTabsTrigger as TabsTrigger } from '@/components/ui/animated-tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { ContentModerationCard } from '@/components/admin/content-moderation-card';
import { ContentItem } from '@/types/content-moderation';
import { useContentModeration } from '@/hooks/use-content-moderation';
import {
    FileText
} from 'lucide-react';

const CONTENT_TYPES = {
    blog_post: {
        label: 'Blog Post',
        description: 'Market insights, neighborhood guides, investment tips'
    },
    social_media: {
        label: 'Social Media',
        description: 'Instagram posts, Facebook updates, LinkedIn articles'
    },
    listing_description: {
        label: 'Listing Description',
        description: 'Property descriptions generated by AI'
    },
    image: {
        label: 'Property Image',
        description: 'Reimagined photos, virtual staging, day-to-dusk'
    },
    market_update: {
        label: 'Market Update',
        description: 'Weekly market reports, trend analysis'
    },
    video_script: {
        label: 'Video Script',
        description: 'Property tours, market updates, educational content'
    }
};

export function ContentClient() {
    const { content, loading, moderateContent } = useContentModeration();
    const [selectedType, setSelectedType] = useState<'all' | ContentItem['type']>('all');
    const [selectedStatus, setSelectedStatus] = useState<'all' | ContentItem['status']>('all');

    const filteredContent = useMemo(() => {
        return content.filter(item => {
            const typeMatch = selectedType === 'all' || item.type === selectedType;
            const statusMatch = selectedStatus === 'all' || item.status === selectedStatus;
            return typeMatch && statusMatch;
        });
    }, [content, selectedType, selectedStatus]);

    const handleModerate = useCallback(async (contentId: string, action: 'approve' | 'reject', reason?: string) => {
        await moderateContent(contentId, action, reason);
    }, [moderateContent]);

    const handleViewDetails = useCallback((contentId: string) => {
        // TODO: Open content details modal/drawer
        console.log('View details for content:', contentId);
    }, []);

    return (
        <div className="space-y-8">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold">Content Moderation</h1>
                    <p className="text-muted-foreground">Review and moderate user-generated content</p>
                </div>
            </div>

            <Tabs defaultValue="all" className="space-y-6">
                <TabsList>
                    <TabsTrigger value="all">All Content</TabsTrigger>
                    <TabsTrigger value="pending">Pending Review</TabsTrigger>
                    <TabsTrigger value="flagged">Flagged</TabsTrigger>
                    <TabsTrigger value="approved">Approved</TabsTrigger>
                    <TabsTrigger value="rejected">Rejected</TabsTrigger>
                </TabsList>

                <div className="flex gap-4">
                    <div className="space-y-2">
                        <Label htmlFor="content-type-filter">Content Type</Label>
                        <Select value={selectedType} onValueChange={(value) => setSelectedType(value as 'all' | ContentItem['type'])}>
                            <SelectTrigger id="content-type-filter" className="w-48">
                                <SelectValue placeholder="Select content type" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All Types</SelectItem>
                                {Object.entries(CONTENT_TYPES).map(([key, type]) => (
                                    <SelectItem key={key} value={key}>{type.label}</SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                    </div>

                    <div className="space-y-2">
                        <Label htmlFor="status-filter">Status</Label>
                        <Select value={selectedStatus} onValueChange={(value) => setSelectedStatus(value as 'all' | ContentItem['status'])}>
                            <SelectTrigger id="status-filter" className="w-48">
                                <SelectValue placeholder="Select status" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All Status</SelectItem>
                                <SelectItem value="pending">Pending</SelectItem>
                                <SelectItem value="approved">Approved</SelectItem>
                                <SelectItem value="rejected">Rejected</SelectItem>
                                <SelectItem value="flagged">Flagged</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                </div>

                <TabsContent value="all" className="space-y-4">
                    {loading ? (
                        <div className="text-center py-12">Loading content...</div>
                    ) : filteredContent.length === 0 ? (
                        <div className="text-center py-12 border-2 border-dashed border-gray-200 dark:border-gray-800 rounded-lg">
                            <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-full w-fit mx-auto mb-4">
                                <FileText className="h-8 w-8 text-gray-400" />
                            </div>
                            <h3 className="text-lg font-semibold mb-2">No content found</h3>
                            <p className="text-muted-foreground">No content matches the current filters</p>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            {filteredContent.map((item) => (
                                <ContentModerationCard
                                    key={item.id}
                                    item={item}
                                    onModerate={handleModerate}
                                    onViewDetails={handleViewDetails}
                                />
                            ))}
                        </div>
                    )}
                </TabsContent>

                <TabsContent value="pending" className="space-y-4">
                    <ContentList
                        items={filteredContent.filter(item => item.status === 'pending')}
                        onModerate={handleModerate}
                        onViewDetails={handleViewDetails}
                    />
                </TabsContent>

                <TabsContent value="flagged" className="space-y-4">
                    <ContentList
                        items={filteredContent.filter(item => item.status === 'flagged')}
                        onModerate={handleModerate}
                        onViewDetails={handleViewDetails}
                    />
                </TabsContent>

                <TabsContent value="approved" className="space-y-4">
                    <ContentList
                        items={filteredContent.filter(item => item.status === 'approved')}
                        onModerate={handleModerate}
                        onViewDetails={handleViewDetails}
                    />
                </TabsContent>

                <TabsContent value="rejected" className="space-y-4">
                    <ContentList
                        items={filteredContent.filter(item => item.status === 'rejected')}
                        onModerate={handleModerate}
                        onViewDetails={handleViewDetails}
                    />
                </TabsContent>
            </Tabs>
        </div>
    );
}

// Extracted Content List Component for better reusability
interface ContentListProps {
    items: ContentItem[];
    onModerate: (contentId: string, action: 'approve' | 'reject', reason?: string) => Promise<void>;
    onViewDetails: (contentId: string) => void;
}

function ContentList({ items, onModerate, onViewDetails }: ContentListProps) {
    if (items.length === 0) {
        return (
            <div className="text-center py-12 border-2 border-dashed border-gray-200 dark:border-gray-800 rounded-lg">
                <div className="p-4 bg-gray-50 dark:bg-gray-900/50 rounded-full w-fit mx-auto mb-4">
                    <FileText className="h-8 w-8 text-gray-400" />
                </div>
                <h3 className="text-lg font-semibold mb-2">No content found</h3>
                <p className="text-muted-foreground">No content matches the current filters</p>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            {items.map((item) => (
                <ContentModerationCard
                    key={item.id}
                    item={item}
                    onModerate={onModerate}
                    onViewDetails={onViewDetails}
                />
            ))}
        </div>
    );
}