'use client';

import { useState, useEffect, useMemo, useCallback } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { AnimatedTabs as Tabs, AnimatedTabsContent as TabsContent, AnimatedTabsList as TabsList, AnimatedTabsTrigger as TabsTrigger } from '@/components/ui/animated-tabs';
import { useToast } from '@/hooks/use-toast';
import { ContentModerationCard } from '@/components/admin/content-moderation-card';
import { ContentItem } from '@/types/content-moderation';
import {
    FileText,
    Filter
} from 'lucide-react';

const CONTENT_TYPES = {
    blog_post: {
        label: 'Blog Post',
        description: 'Market insights, neighborhood guides, investment tips'
    },
    social_media: {
        label: 'Social Media',
        description: 'Instagram posts, Facebook updates, LinkedIn articles'
    },
    listing_description: {
        label: 'Listing Description',
        description: 'Property descriptions generated by AI'
    },
    image: {
        label: 'Property Image',
        description: 'Reimagined photos, virtual staging, day-to-dusk'
    },
    video: {
        label: 'Video Content',
        description: 'Property tours, market updates, educational content'
    }
} as const;

export default function SuperAdminContentPage() {
    const [content, setContent] = useState<ContentItem[]>([]);
    const [loading, setLoading] = useState(true);
    const [statusFilter, setStatusFilter] = useState('all');
    const [typeFilter, setTypeFilter] = useState('all');
    const { toast } = useToast();

    useEffect(() => {
        loadContent();
    }, [statusFilter, typeFilter]);

    async function loadContent() {
        try {
            setLoading(true);
            // Mock data - replace with actual API call
            const mockContent: ContentItem[] = [
                {
                    id: '1',
                    type: 'blog_post',
                    title: 'Top 10 Real Estate Investment Tips for 2024',
                    content: 'Real estate investment continues to be one of the most reliable ways to build wealth...',
                    status: 'pending',
                    userId: 'user-123',
                    userName: 'John Doe',
                    userEmail: 'john.doe@example.com',
                    createdAt: new Date(Date.now() - 3600000).toISOString()
                },
                {
                    id: '2',
                    type: 'social_media',
                    title: 'Market Update Post',
                    content: 'The housing market is showing strong signs of recovery...',
                    status: 'flagged',
                    userId: 'user-456',
                    userName: 'Jane Smith',
                    userEmail: 'jane.smith@example.com',
                    createdAt: new Date(Date.now() - 7200000).toISOString(),
                    flagReason: 'Potentially misleading market claims'
                }
            ];

            let filtered = mockContent;
            if (statusFilter !== 'all') {
                filtered = filtered.filter(item => item.status === statusFilter);
            }
            if (typeFilter !== 'all') {
                filtered = filtered.filter(item => item.type === typeFilter);
            }
            setContent(filtered);
        } catch (error) {
            console.error('Failed to load content:', error);
            toast({
                title: "Error",
                description: "Failed to load content",
                variant: "destructive"
            });
        } finally {
            setLoading(false);
        }
    }

    const moderateContent = useCallback(async (contentId: string, action: 'approve' | 'reject', reason?: string) => {
        try {
            // TODO: Implement actual moderation API call
            setContent(prev => prev.map(item =>
                item.id === contentId
                    ? { ...item, status: action === 'approve' ? 'approved' : 'rejected', moderatedAt: new Date().toISOString() }
                    : item
            ));

            toast({
                title: "Success",
                description: `Content ${action}d successfully`
            });
        } catch (error) {
            toast({
                title: "Error",
                description: `Failed to ${action} content`,
                variant: "destructive"
            });
        }
    }, [toast]);

    const handleViewDetails = useCallback((contentId: string) => {
        // TODO: Implement content details modal or navigation
        console.log('View details for content:', contentId);
    }, []);

    // Memoize filtered content to avoid recalculation on every render
    const filteredContent = useMemo(() => {
        let filtered = content;
        if (statusFilter !== 'all') {
            filtered = filtered.filter(item => item.status === statusFilter);
        }
        if (typeFilter !== 'all') {
            filtered = filtered.filter(item => item.type === typeFilter);
        }
        return filtered;
    }, [content, statusFilter, typeFilter]);

    return (
        <div className="space-y-8">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-3xl font-bold tracking-tight">Content Moderation</h2>
                    <p className="text-muted-foreground">Review and moderate user-generated content</p>
                </div>
            </div>

            <Tabs defaultValue="all" className="space-y-6">
                <TabsList className="grid w-full grid-cols-5">
                    <TabsTrigger value="all" onClick={() => setStatusFilter('all')}>All</TabsTrigger>
                    <TabsTrigger value="pending" onClick={() => setStatusFilter('pending')}>Pending</TabsTrigger>
                    <TabsTrigger value="flagged" onClick={() => setStatusFilter('flagged')}>Flagged</TabsTrigger>
                    <TabsTrigger value="approved" onClick={() => setStatusFilter('approved')}>Approved</TabsTrigger>
                    <TabsTrigger value="rejected" onClick={() => setStatusFilter('rejected')}>Rejected</TabsTrigger>
                </TabsList>

                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2">
                        <Filter className="h-4 w-4" />
                        <select
                            value={typeFilter}
                            onChange={(e) => setTypeFilter(e.target.value)}
                            className="border rounded px-3 py-1"
                        >
                            <option value="all">All Types</option>
                            {Object.entries(CONTENT_TYPES).map(([key, config]) => (
                                <option key={key} value={key}>{config.label}</option>
                            ))}
                        </select>
                    </div>
                </div>

                <TabsContent value="all" className="space-y-4">
                    {loading ? (
                        <Card>
                            <CardContent className="flex items-center justify-center py-12">
                                <div className="text-muted-foreground">Loading content...</div>
                            </CardContent>
                        </Card>
                    ) : content.length === 0 ? (
                        <Card>
                            <CardContent className="flex flex-col items-center justify-center py-12">
                                <FileText className="h-12 w-12 text-muted-foreground mb-4" />
                                <h3 className="text-lg font-semibold mb-2">No Content Found</h3>
                                <p className="text-muted-foreground text-center">
                                    No content matches the current filters
                                </p>
                            </CardContent>
                        </Card>
                    ) : (
                        <div className="space-y-4">
                            {filteredContent.map((item) => (
                                <ContentModerationCard
                                    key={item.id}
                                    item={item}
                                    onModerate={moderateContent}
                                    onViewDetails={handleViewDetails}
                                />
                            ))}
                        </div>
                    )}
                </TabsContent>

                {/* Other tab contents would be similar but filtered */}
                <TabsContent value="pending">
                    {/* Same content structure but filtered for pending items */}
                </TabsContent>
                <TabsContent value="flagged">
                    {/* Same content structure but filtered for flagged items */}
                </TabsContent>
                <TabsContent value="approved">
                    {/* Same content structure but filtered for approved items */}
                </TabsContent>
                <TabsContent value="rejected">
                    {/* Same content structure but filtered for rejected items */}
                </TabsContent>
            </Tabs>
        </div>
    );
}