'use client';

import { useState } from 'react';
import { StandardCard } from '@/components/standard/card';
import { StandardFormField } from '@/components/standard/form-field';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Loader2, Sparkles, Save, Download } from 'lucide-react';
import { generateTrainingPlanAction, saveTrainingPlanAction } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';

export interface AITrainingPlanProps {
    className?: string;
}

export function AITrainingPlan({ className }: AITrainingPlanProps = {}) {
    const [challenge, setChallenge] = useState('');
    const [plan, setPlan] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const { toast } = useToast();

    const handleGenerate = async () => {
        if (!challenge.trim()) {
            toast({
                title: 'Input Required',
                description: 'Please describe your challenge or growth area.',
                variant: 'destructive',
            });
            return;
        }

        setIsGenerating(true);
        setPlan('');

        try {
            const result = await generateTrainingPlanAction(challenge);

            if (result.errors) {
                console.error('Training plan errors:', result.errors);
                toast({
                    title: 'Generation Failed',
                    description: result.errors.join(', '),
                    variant: 'destructive',
                });
            } else if (result.data?.plan) {
                setPlan(result.data.plan);
                toast({
                    title: 'Training Plan Generated',
                    description: 'Your personalized plan is ready!',
                });
            } else {
                console.error('No plan data returned:', result);
                toast({
                    title: 'Generation Failed',
                    description: 'No training plan was generated. Please try again.',
                    variant: 'destructive',
                });
            }
        } catch (error) {
            console.error('Training plan generation error:', error);
            const errorMessage = error instanceof Error ? error.message : 'Unknown error';
            toast({
                title: 'Error',
                description: `Failed: ${errorMessage}`,
                variant: 'destructive',
            });
        } finally {
            setIsGenerating(false);
        }
    };

    const handleSave = async () => {
        if (!plan || !challenge) return;

        setIsSaving(true);
        try {
            const result = await saveTrainingPlanAction(challenge, plan);

            if (result.errors) {
                toast({
                    title: 'Save Failed',
                    description: result.errors.join(', '),
                    variant: 'destructive',
                });
            } else {
                toast({
                    title: 'Training Plan Saved',
                    description: 'Your plan has been saved to your knowledge base.',
                });
            }
        } catch (error) {
            console.error('Save error:', error);
            toast({
                title: 'Error',
                description: 'Failed to save training plan.',
                variant: 'destructive',
            });
        } finally {
            setIsSaving(false);
        }
    };

    const handleDownload = () => {
        if (!plan) return;

        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Training Plan - ${challenge.substring(0, 50)}</title>
    <style>
        body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        h3 { color: #1a1a1a; margin-top: 24px; margin-bottom: 12px; font-size: 1.25rem; font-weight: 600; }
        h4 { color: #333; margin-top: 16px; margin-bottom: 8px; font-weight: 600; }
        p { margin-top: 8px; color: #4a4a4a; }
        ul, ol { margin-left: 24px; margin-top: 8px; }
        li { margin-top: 8px; }
        strong { font-weight: 600; color: #1a1a1a; }
        .header { border-bottom: 2px solid #e5e5e5; padding-bottom: 16px; margin-bottom: 24px; }
        .challenge { background: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Your Personalized Training Plan</h1>
        <p>Generated by Bayon Coagent</p>
    </div>
    <div class="challenge">
        <strong>Challenge:</strong> ${challenge}
    </div>
    ${plan}
</body>
</html>
        `;

        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `training-plan-${Date.now()}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        toast({
            title: 'Downloaded',
            description: 'Training plan downloaded as HTML file.',
        });
    };

    return (
        <StandardCard
            title={<span className="font-headline">AI Training Plan Generator</span>}
            description="Describe your challenge or growth area, and get a personalized training plan"
        >
            <div className="space-y-6">
                <StandardFormField
                    label="What's your growth area?"
                    id="challenge"
                    hint="💡 Tip: The more specific you are, the more tailored your training plan will be."
                >
                    <Textarea
                        id="challenge"
                        placeholder="Example: I struggle with following up with leads consistently, or I want to improve my social media presence but don't know where to start..."
                        value={challenge}
                        onChange={(e) => setChallenge(e.target.value)}
                        rows={4}
                        className="resize-none"
                    />
                </StandardFormField>

                <Button
                    onClick={handleGenerate}
                    disabled={isGenerating || !challenge.trim()}
                    className="w-full h-12 text-base font-semibold bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70"
                    size="lg"
                >
                    {isGenerating ? (
                        <>
                            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                            Generating Your Plan...
                        </>
                    ) : (
                        <>
                            <Sparkles className="mr-2 h-5 w-5" />
                            Generate Training Plan
                        </>
                    )}
                </Button>

                {plan && (
                    <div className="space-y-4 animate-fade-in-up">
                        <div className="flex flex-col sm:flex-row gap-2">
                            <Button
                                onClick={handleSave}
                                disabled={isSaving}
                                variant="outline"
                                className="flex-1"
                            >
                                {isSaving ? (
                                    <>
                                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                        Saving...
                                    </>
                                ) : (
                                    <>
                                        <Save className="mr-2 h-4 w-4" />
                                        Save to Knowledge Base
                                    </>
                                )}
                            </Button>
                            <Button
                                onClick={handleDownload}
                                variant="outline"
                                className="flex-1"
                            >
                                <Download className="mr-2 h-4 w-4" />
                                Download as HTML
                            </Button>
                        </div>
                        <div className="p-6 bg-gradient-to-br from-secondary/50 to-secondary/30 rounded-lg border-2 border-primary/10">
                            <div className="flex items-center gap-2 mb-4">
                                <div className="h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center">
                                    <Sparkles className="h-4 w-4 text-primary" />
                                </div>
                                <h3 className="font-semibold text-lg">Your Personalized Training Plan</h3>
                            </div>
                            <div
                                className="prose prose-sm md:prose-base max-w-none text-foreground/80 dark:prose-invert prose-headings:text-foreground prose-a:text-primary prose-strong:text-foreground"
                                dangerouslySetInnerHTML={{ __html: plan }}
                            />
                        </div>
                    </div>
                )}
            </div>
        </StandardCard>
    );
}
