#!/bin/bash

# Script to update .env file with CDK outputs
# Usage: ./update-env.sh [environment]

set -e

ENVIRONMENT=${1:-development}
OUTPUTS_FILE="outputs.json"
ENV_FILE="../.env.${ENVIRONMENT}"

if [ ! -f "$OUTPUTS_FILE" ]; then
    echo "Error: outputs.json not found. Run deployment first."
    exit 1
fi

echo "Updating ${ENV_FILE} with CDK outputs..."

# Extract values from outputs.json using jq
USER_POOL_ID=$(jq -r ".\"BayonCoAgent-${ENVIRONMENT}-Cognito\".UserPoolId" $OUTPUTS_FILE)
USER_POOL_CLIENT_ID=$(jq -r ".\"BayonCoAgent-${ENVIRONMENT}-Cognito\".UserPoolClientId" $OUTPUTS_FILE)
IDENTITY_POOL_ID=$(jq -r ".\"BayonCoAgent-${ENVIRONMENT}-Cognito\".IdentityPoolId" $OUTPUTS_FILE)
DYNAMODB_TABLE_NAME=$(jq -r ".\"BayonCoAgent-${ENVIRONMENT}-DynamoDB\".TableName" $OUTPUTS_FILE)
S3_BUCKET_NAME=$(jq -r ".\"BayonCoAgent-${ENVIRONMENT}-S3\".StorageBucketName" $OUTPUTS_FILE)

# Create or update .env file
cat > $ENV_FILE << EOF
# AWS Configuration - Generated by CDK deployment
# Environment: ${ENVIRONMENT}
# Generated: $(date)

# AWS Region
AWS_REGION=us-west-2

# Cognito Configuration
COGNITO_USER_POOL_ID=${USER_POOL_ID}
COGNITO_CLIENT_ID=${USER_POOL_CLIENT_ID}
COGNITO_IDENTITY_POOL_ID=${IDENTITY_POOL_ID}

# DynamoDB Configuration
DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}

# S3 Configuration
S3_BUCKET_NAME=${S3_BUCKET_NAME}

# Bedrock Configuration
BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0
BEDROCK_REGION=us-west-2

# Application Configuration
NODE_ENV=${ENVIRONMENT}
USE_LOCAL_AWS=false
EOF

echo "✓ Environment file updated: ${ENV_FILE}"
echo ""
echo "Copy the values to your application's .env file:"
echo "  cp ${ENV_FILE} ../.env.production"
