#!/bin/bash

# Script to update .env file with SAM outputs
# Usage: ./update-env-from-sam.sh [environment]

set -e

ENVIRONMENT=${1:-development}
PROFILE=${AWS_PROFILE:-default}
REGION=${AWS_REGION:-us-east-1}
STACK_NAME="bayon-coagent-${ENVIRONMENT}"
ENV_FILE=".env.${ENVIRONMENT}"

echo "Retrieving stack outputs from ${STACK_NAME}..."

# Get outputs from CloudFormation
USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --profile $PROFILE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
    --output text)

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --profile $PROFILE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
    --output text)

IDENTITY_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --profile $PROFILE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`IdentityPoolId`].OutputValue' \
    --output text)

DYNAMODB_TABLE_NAME=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --profile $PROFILE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`DynamoDBTableName`].OutputValue' \
    --output text)

S3_BUCKET_NAME=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --profile $PROFILE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`StorageBucketName`].OutputValue' \
    --output text)

# Create or update .env file
cat > $ENV_FILE << EOF
# AWS Configuration - Generated by SAM deployment
# Environment: ${ENVIRONMENT}
# Generated: $(date)

# AWS Region
AWS_REGION=${REGION}

# Cognito Configuration
COGNITO_USER_POOL_ID=${USER_POOL_ID}
COGNITO_CLIENT_ID=${USER_POOL_CLIENT_ID}
COGNITO_IDENTITY_POOL_ID=${IDENTITY_POOL_ID}

# DynamoDB Configuration
DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}

# S3 Configuration
S3_BUCKET_NAME=${S3_BUCKET_NAME}

# Bedrock Configuration
BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0
BEDROCK_REGION=${REGION}

# Application Configuration
NODE_ENV=${ENVIRONMENT}
USE_LOCAL_AWS=false
EOF

echo "✓ Environment file created: ${ENV_FILE}"
echo ""
echo "Copy the values to your application's .env file:"
if [ "$ENVIRONMENT" == "production" ]; then
    echo "  cp ${ENV_FILE} .env.production"
else
    echo "  cp ${ENV_FILE} .env.local"
fi
echo ""
echo "Configuration values:"
echo "  User Pool ID:     ${USER_POOL_ID}"
echo "  Client ID:        ${USER_POOL_CLIENT_ID}"
echo "  Identity Pool ID: ${IDENTITY_POOL_ID}"
echo "  DynamoDB Table:   ${DYNAMODB_TABLE_NAME}"
echo "  S3 Bucket:        ${S3_BUCKET_NAME}"
